# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:21:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class EncodingType(Enum):
    NONE = 'NONE'
    UTF8 = 'UTF8'
    UTF16 = 'UTF16'
    UTF32 = 'UTF32'


class Label(Enum):
    UNKNOWN = 'UNKNOWN'
    ABBREV = 'ABBREV'
    ACOMP = 'ACOMP'
    ADVCL = 'ADVCL'
    ADVMOD = 'ADVMOD'
    AMOD = 'AMOD'
    APPOS = 'APPOS'
    ATTR = 'ATTR'
    AUX = 'AUX'
    AUXPASS = 'AUXPASS'
    CC = 'CC'
    CCOMP = 'CCOMP'
    CONJ = 'CONJ'
    CSUBJ = 'CSUBJ'
    CSUBJPASS = 'CSUBJPASS'
    DEP = 'DEP'
    DET = 'DET'
    DISCOURSE = 'DISCOURSE'
    DOBJ = 'DOBJ'
    EXPL = 'EXPL'
    GOESWITH = 'GOESWITH'
    IOBJ = 'IOBJ'
    MARK = 'MARK'
    MWE = 'MWE'
    MWV = 'MWV'
    NEG = 'NEG'
    NN = 'NN'
    NPADVMOD = 'NPADVMOD'
    NSUBJ = 'NSUBJ'
    NSUBJPASS = 'NSUBJPASS'
    NUM = 'NUM'
    NUMBER = 'NUMBER'
    P = 'P'
    PARATAXIS = 'PARATAXIS'
    PARTMOD = 'PARTMOD'
    PCOMP = 'PCOMP'
    POBJ = 'POBJ'
    POSS = 'POSS'
    POSTNEG = 'POSTNEG'
    PRECOMP = 'PRECOMP'
    PRECONJ = 'PRECONJ'
    PREDET = 'PREDET'
    PREF = 'PREF'
    PREP = 'PREP'
    PRONL = 'PRONL'
    PRT = 'PRT'
    PS = 'PS'
    QUANTMOD = 'QUANTMOD'
    RCMOD = 'RCMOD'
    RCMODREL = 'RCMODREL'
    RDROP = 'RDROP'
    REF = 'REF'
    REMNANT = 'REMNANT'
    REPARANDUM = 'REPARANDUM'
    ROOT = 'ROOT'
    SNUM = 'SNUM'
    SUFF = 'SUFF'
    TMOD = 'TMOD'
    TOPIC = 'TOPIC'
    VMOD = 'VMOD'
    VOCATIVE = 'VOCATIVE'
    XCOMP = 'XCOMP'
    SUFFIX = 'SUFFIX'
    TITLE = 'TITLE'
    ADVPHMOD = 'ADVPHMOD'
    AUXCAUS = 'AUXCAUS'
    AUXVV = 'AUXVV'
    DTMOD = 'DTMOD'
    FOREIGN = 'FOREIGN'
    KW = 'KW'
    LIST = 'LIST'
    NOMC = 'NOMC'
    NOMCSUBJ = 'NOMCSUBJ'
    NOMCSUBJPASS = 'NOMCSUBJPASS'
    NUMC = 'NUMC'
    COP = 'COP'
    DISLOCATED = 'DISLOCATED'
    ASP = 'ASP'
    GMOD = 'GMOD'
    GOBJ = 'GOBJ'
    INFMOD = 'INFMOD'
    MES = 'MES'
    NCOMP = 'NCOMP'


class DependencyEdge(BaseModel):
    headTokenIndex: Optional[int] = Field(
        None,
        description='Represents the head of this token in the dependency tree. This is the index of the token which has an arc going to this token. The index is the position of the token in the array of tokens returned by the API method. If this token is a root token, then the `head_token_index` is its own index.',
    )
    label: Optional[Label] = Field(None, description='The parse label for the token.')


class Type(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    PLAIN_TEXT = 'PLAIN_TEXT'
    HTML = 'HTML'


class Document(BaseModel):
    content: Optional[str] = Field(
        None,
        description='The content of the input in string format. Cloud audit logging exempt since it is based on user data.',
    )
    gcsContentUri: Optional[str] = Field(
        None,
        description='The Google Cloud Storage URI where the file content is located. This URI must be of the form: gs://bucket_name/object_name. For more details, see https://cloud.google.com/storage/docs/reference-uris. NOTE: Cloud Storage object versioning is not supported.',
    )
    language: Optional[str] = Field(
        None,
        description='The language of the document (if not specified, the language is automatically detected). Both ISO and BCP-47 language codes are accepted. [Language Support](https://cloud.google.com/natural-language/docs/languages) lists currently supported languages for each API method. If the language (either specified by the caller or automatically detected) is not supported by the called API method, an `INVALID_ARGUMENT` error is returned.',
    )
    type: Optional[Type] = Field(
        None,
        description='Required. If the type is not set or is `TYPE_UNSPECIFIED`, returns an `INVALID_ARGUMENT` error.',
    )


class Type1(Enum):
    UNKNOWN = 'UNKNOWN'
    PERSON = 'PERSON'
    LOCATION = 'LOCATION'
    ORGANIZATION = 'ORGANIZATION'
    EVENT = 'EVENT'
    WORK_OF_ART = 'WORK_OF_ART'
    CONSUMER_GOOD = 'CONSUMER_GOOD'
    OTHER = 'OTHER'


class Type2(Enum):
    TYPE_UNKNOWN = 'TYPE_UNKNOWN'
    PROPER = 'PROPER'
    COMMON = 'COMMON'


class Features(BaseModel):
    extractDocumentSentiment: Optional[bool] = Field(
        None, description='Extract document-level sentiment.'
    )
    extractEntities: Optional[bool] = Field(None, description='Extract entities.')
    extractSyntax: Optional[bool] = Field(
        None, description='Extract syntax information.'
    )


class Aspect(Enum):
    ASPECT_UNKNOWN = 'ASPECT_UNKNOWN'
    PERFECTIVE = 'PERFECTIVE'
    IMPERFECTIVE = 'IMPERFECTIVE'
    PROGRESSIVE = 'PROGRESSIVE'


class Case(Enum):
    CASE_UNKNOWN = 'CASE_UNKNOWN'
    ACCUSATIVE = 'ACCUSATIVE'
    ADVERBIAL = 'ADVERBIAL'
    COMPLEMENTIVE = 'COMPLEMENTIVE'
    DATIVE = 'DATIVE'
    GENITIVE = 'GENITIVE'
    INSTRUMENTAL = 'INSTRUMENTAL'
    LOCATIVE = 'LOCATIVE'
    NOMINATIVE = 'NOMINATIVE'
    OBLIQUE = 'OBLIQUE'
    PARTITIVE = 'PARTITIVE'
    PREPOSITIONAL = 'PREPOSITIONAL'
    REFLEXIVE_CASE = 'REFLEXIVE_CASE'
    RELATIVE_CASE = 'RELATIVE_CASE'
    VOCATIVE = 'VOCATIVE'


class Form(Enum):
    FORM_UNKNOWN = 'FORM_UNKNOWN'
    ADNOMIAL = 'ADNOMIAL'
    AUXILIARY = 'AUXILIARY'
    COMPLEMENTIZER = 'COMPLEMENTIZER'
    FINAL_ENDING = 'FINAL_ENDING'
    GERUND = 'GERUND'
    REALIS = 'REALIS'
    IRREALIS = 'IRREALIS'
    SHORT = 'SHORT'
    LONG = 'LONG'
    ORDER = 'ORDER'
    SPECIFIC = 'SPECIFIC'


class Gender(Enum):
    GENDER_UNKNOWN = 'GENDER_UNKNOWN'
    FEMININE = 'FEMININE'
    MASCULINE = 'MASCULINE'
    NEUTER = 'NEUTER'


class Mood(Enum):
    MOOD_UNKNOWN = 'MOOD_UNKNOWN'
    CONDITIONAL_MOOD = 'CONDITIONAL_MOOD'
    IMPERATIVE = 'IMPERATIVE'
    INDICATIVE = 'INDICATIVE'
    INTERROGATIVE = 'INTERROGATIVE'
    JUSSIVE = 'JUSSIVE'
    SUBJUNCTIVE = 'SUBJUNCTIVE'


class Number(Enum):
    NUMBER_UNKNOWN = 'NUMBER_UNKNOWN'
    SINGULAR = 'SINGULAR'
    PLURAL = 'PLURAL'
    DUAL = 'DUAL'


class Person(Enum):
    PERSON_UNKNOWN = 'PERSON_UNKNOWN'
    FIRST = 'FIRST'
    SECOND = 'SECOND'
    THIRD = 'THIRD'
    REFLEXIVE_PERSON = 'REFLEXIVE_PERSON'


class Proper(Enum):
    PROPER_UNKNOWN = 'PROPER_UNKNOWN'
    PROPER = 'PROPER'
    NOT_PROPER = 'NOT_PROPER'


class Reciprocity(Enum):
    RECIPROCITY_UNKNOWN = 'RECIPROCITY_UNKNOWN'
    RECIPROCAL = 'RECIPROCAL'
    NON_RECIPROCAL = 'NON_RECIPROCAL'


class Tag(Enum):
    UNKNOWN = 'UNKNOWN'
    ADJ = 'ADJ'
    ADP = 'ADP'
    ADV = 'ADV'
    CONJ = 'CONJ'
    DET = 'DET'
    NOUN = 'NOUN'
    NUM = 'NUM'
    PRON = 'PRON'
    PRT = 'PRT'
    PUNCT = 'PUNCT'
    VERB = 'VERB'
    X = 'X'
    AFFIX = 'AFFIX'


class Tense(Enum):
    TENSE_UNKNOWN = 'TENSE_UNKNOWN'
    CONDITIONAL_TENSE = 'CONDITIONAL_TENSE'
    FUTURE = 'FUTURE'
    PAST = 'PAST'
    PRESENT = 'PRESENT'
    IMPERFECT = 'IMPERFECT'
    PLUPERFECT = 'PLUPERFECT'


class Voice(Enum):
    VOICE_UNKNOWN = 'VOICE_UNKNOWN'
    ACTIVE = 'ACTIVE'
    CAUSATIVE = 'CAUSATIVE'
    PASSIVE = 'PASSIVE'


class PartOfSpeech(BaseModel):
    aspect: Optional[Aspect] = Field(None, description='The grammatical aspect.')
    case: Optional[Case] = Field(None, description='The grammatical case.')
    form: Optional[Form] = Field(None, description='The grammatical form.')
    gender: Optional[Gender] = Field(None, description='The grammatical gender.')
    mood: Optional[Mood] = Field(None, description='The grammatical mood.')
    number: Optional[Number] = Field(None, description='The grammatical number.')
    person: Optional[Person] = Field(None, description='The grammatical person.')
    proper: Optional[Proper] = Field(None, description='The grammatical properness.')
    reciprocity: Optional[Reciprocity] = Field(
        None, description='The grammatical reciprocity.'
    )
    tag: Optional[Tag] = Field(None, description='The part of speech tag.')
    tense: Optional[Tense] = Field(None, description='The grammatical tense.')
    voice: Optional[Voice] = Field(None, description='The grammatical voice.')


class Sentiment(BaseModel):
    magnitude: Optional[float] = Field(
        None,
        description='A non-negative number in the [0, +inf) range, which represents the absolute magnitude of sentiment regardless of score (positive or negative).',
    )
    polarity: Optional[float] = Field(
        None,
        description='DEPRECATED FIELD - This field is being deprecated in favor of score. Please refer to our documentation at https://cloud.google.com/natural-language/docs for more information.',
    )
    score: Optional[float] = Field(
        None,
        description='Sentiment score between -1.0 (negative sentiment) and 1.0 (positive sentiment).',
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TextSpan(BaseModel):
    beginOffset: Optional[int] = Field(
        None,
        description='The API calculates the beginning offset of the content in the original document according to the EncodingType specified in the API request.',
    )
    content: Optional[str] = Field(None, description='The content of the output text.')


class Token(BaseModel):
    dependencyEdge: Optional[DependencyEdge] = Field(
        None, description='Dependency tree parse for this token.'
    )
    lemma: Optional[str] = Field(
        None,
        description='[Lemma](https://en.wikipedia.org/wiki/Lemma_%28morphology%29) of the token.',
    )
    partOfSpeech: Optional[PartOfSpeech] = Field(
        None, description='Parts of speech tag for this token.'
    )
    text: Optional[TextSpan] = Field(None, description='The token text.')


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class AnalyzeEntitiesRequest(BaseModel):
    document: Optional[Document] = Field(None, description='Input document.')
    encodingType: Optional[EncodingType] = Field(
        None, description='The encoding type used by the API to calculate offsets.'
    )


class AnalyzeSentimentRequest(BaseModel):
    document: Optional[Document] = Field(None, description='Input document.')
    encodingType: Optional[EncodingType] = Field(
        None,
        description='The encoding type used by the API to calculate sentence offsets for the sentence sentiment.',
    )


class AnalyzeSyntaxRequest(BaseModel):
    document: Optional[Document] = Field(None, description='Input document.')
    encodingType: Optional[EncodingType] = Field(
        None, description='The encoding type used by the API to calculate offsets.'
    )


class AnnotateTextRequest(BaseModel):
    document: Optional[Document] = Field(None, description='Input document.')
    encodingType: Optional[EncodingType] = Field(
        None, description='The encoding type used by the API to calculate offsets.'
    )
    features: Optional[Features] = Field(None, description='The enabled features.')


class EntityMention(BaseModel):
    text: Optional[TextSpan] = Field(None, description='The mention text.')
    type: Optional[Type2] = Field(None, description='The type of the entity mention.')


class Sentence(BaseModel):
    sentiment: Optional[Sentiment] = Field(
        None,
        description='For calls to AnalyzeSentiment or if AnnotateTextRequest.Features.extract_document_sentiment is set to true, this field will contain the sentiment for the sentence.',
    )
    text: Optional[TextSpan] = Field(None, description='The sentence text.')


class AnalyzeSentimentResponse(BaseModel):
    documentSentiment: Optional[Sentiment] = Field(
        None, description='The overall sentiment of the input document.'
    )
    language: Optional[str] = Field(
        None,
        description='The language of the text, which will be the same as the language specified in the request or, if not specified, the automatically-detected language. See Document.language field for more details.',
    )
    sentences: Optional[List[Sentence]] = Field(
        None, description='The sentiment for all the sentences in the document.'
    )


class AnalyzeSyntaxResponse(BaseModel):
    language: Optional[str] = Field(
        None,
        description='The language of the text, which will be the same as the language specified in the request or, if not specified, the automatically-detected language. See Document.language field for more details.',
    )
    sentences: Optional[List[Sentence]] = Field(
        None, description='Sentences in the input document.'
    )
    tokens: Optional[List[Token]] = Field(
        None,
        description='Tokens, along with their syntactic information, in the input document.',
    )


class Entity(BaseModel):
    mentions: Optional[List[EntityMention]] = Field(
        None,
        description='The mentions of this entity in the input document. The API currently supports proper noun mentions.',
    )
    metadata: Optional[Dict[str, str]] = Field(
        None,
        description='Metadata associated with the entity. Currently, Wikipedia URLs and Knowledge Graph MIDs are provided, if available. The associated keys are "wikipedia_url" and "mid", respectively.',
    )
    name: Optional[str] = Field(
        None, description='The representative name for the entity.'
    )
    salience: Optional[float] = Field(
        None,
        description='The salience score associated with the entity in the [0, 1.0] range. The salience score for an entity provides information about the importance or centrality of that entity to the entire document text. Scores closer to 0 are less salient, while scores closer to 1.0 are highly salient.',
    )
    type: Optional[Type1] = Field(None, description='The entity type.')


class AnalyzeEntitiesResponse(BaseModel):
    entities: Optional[List[Entity]] = Field(
        None, description='The recognized entities in the input document.'
    )
    language: Optional[str] = Field(
        None,
        description='The language of the text, which will be the same as the language specified in the request or, if not specified, the automatically-detected language. See Document.language field for more details.',
    )


class AnnotateTextResponse(BaseModel):
    documentSentiment: Optional[Sentiment] = Field(
        None,
        description='The overall sentiment for the document. Populated if the user enables AnnotateTextRequest.Features.extract_document_sentiment.',
    )
    entities: Optional[List[Entity]] = Field(
        None,
        description='Entities, along with their semantic information, in the input document. Populated if the user enables AnnotateTextRequest.Features.extract_entities.',
    )
    language: Optional[str] = Field(
        None,
        description='The language of the text, which will be the same as the language specified in the request or, if not specified, the automatically-detected language. See Document.language field for more details.',
    )
    sentences: Optional[List[Sentence]] = Field(
        None,
        description='Sentences in the input document. Populated if the user enables AnnotateTextRequest.Features.extract_syntax.',
    )
    tokens: Optional[List[Token]] = Field(
        None,
        description='Tokens, along with their syntactic information, in the input document. Populated if the user enables AnnotateTextRequest.Features.extract_syntax.',
    )
